Repository facebook/ds2, pull requests merged in 2018-03, with the labels that each got.

#598 Enable logs on CircleCI lldb tests
  .circleci/config.yml
Labels: CLA Signed, Please Review, self-contained

#599 Use -rdynamic for non-static ds2 builds
  CMakeLists.txt
Labels: CLA Signed

#601 Update instructions for running docker image locally
  Support/Testing/CircleCI/Dockerfile
Labels: CLA Signed, Please Review

#602 Remove dead patches
  Support/Testing/Patches/lldb-blacklist-update.patch
  Support/Testing/Patches/lldb-test-blacklist.patch
  Support/Testing/Patches/memory-region-info.patch
Labels: CLA Signed

#604 Update docker instructions to talk about tags and how we use them
  Support/Testing/CircleCI/Dockerfile
Labels: CLA Signed
