Repository facebook/ds2, pull requests merged in 2018-02, with the labels that each got.

#541 Enable VS 2017 builds for Windows
  .appveyor.yml
Labels: CLA Signed, Continuous Integration

#587 Remove Go tests from blacklists
  Support/Testing/Blacklists/ds2/x86.blacklist
Labels: CLA Signed, Continuous Integration

#588 Remove MiniDump from the ds2 test blacklists
  Support/Scripts/run-lldb-tests.sh
  Support/Testing/Blacklists/ds2/x86-platform.blacklist
Labels: CLA Signed, Continuous Integration

#593 Enable a few tests in upstream blacklists
  Support/Testing/Blacklists/upstream/general.blacklist
  Support/Testing/Blacklists/upstream/x86.blacklist
Labels: CLA Signed

#590 Re-enable upstream platform tests
  Support/Testing/Blacklists/upstream/platform.blacklist
Labels: CLA Signed, Continuous Integration

#572 Simplify ELFSupport::MachineTypeToCPUType
  Sources/Host/Linux/ProcFS.cpp
  Sources/Support/POSIX/ELFSupport.cpp
Labels: CLA Signed, freebsd, linux, self-contained

#596 Disable TestQuoting in platform mode
  Support/Testing/Blacklists/ds2/platform.blacklist
Labels: CLA Signed
