Repository facebook/ds2, pull requests merged in 2018-04, with the labels that each got.

#574 add --fd option
  Headers/DebugServer2/Host/Socket.h
  Sources/Host/Common/Socket.cpp
  Sources/main.cpp
Labels: CLA Signed

#606 Rename Type in BreakpointManager to Lifetime
  Headers/DebugServer2/Core/BreakpointManager.h
  Headers/DebugServer2/Core/HardwareBreakpointManager.h
  Headers/DebugServer2/Core/SoftwareBreakpointManager.h
  Sources/Architecture/ARM/SoftwareSingleStep.cpp
  Sources/Core/ARM/SoftwareBreakpointManager.cpp
  Sources/Core/BreakpointManager.cpp
  Sources/Core/HardwareBreakpointManager.cpp
  Sources/GDBRemote/DebugSessionImpl.cpp
Labels: CLA Signed

#608 Simplify compiler support code
  Headers/DebugServer2/Utils/Bits.h
  Headers/DebugServer2/Utils/CompilerSupport.h
Labels: CLA Signed, android

#607 Remove assertions and add debug logs to breakpoint validation code
  Sources/Core/ARM/HardwareBreakpointManager.cpp
  Sources/Core/ARM/SoftwareBreakpointManager.cpp
  Sources/Core/X86/HardwareBreakpointManager.cpp
  Sources/Core/X86/SoftwareBreakpointManager.cpp
Labels: CLA Signed, Please Review, self-contained

#609 Add support for choosing breakpoint sizes
  Headers/DebugServer2/Core/BreakpointManager.h
  Headers/DebugServer2/Core/HardwareBreakpointManager.h
  Headers/DebugServer2/Core/SoftwareBreakpointManager.h
  Sources/Core/ARM/HardwareBreakpointManager.cpp
  Sources/Core/ARM/SoftwareBreakpointManager.cpp
  Sources/Core/BreakpointManager.cpp
  Sources/Core/X86/HardwareBreakpointManager.cpp
  Sources/Core/X86/SoftwareBreakpointManager.cpp
Labels: CLA Signed, Please Review

#610 Improve run-lldb-tests.sh
  Support/Scripts/run-lldb-tests.sh
Labels: CLA Signed
